name: Hello World with GitHub Actions
on:
  push:
    branches:
      - developer
Jobs:
    Hello-World:
      needs: [start_developer_branch]
      runs-on: ubuntu-latest
      steps:
        - name: Hello World
          run: echo "Hello World"
