name: Hello World with GitHub Actions
on:
  push:
    branches:
      - developer
  jobs:
    start_developer_branch:
      runs-on: ubuntu-latest
      steps:
        - name: Start developer branch
          run: echo "Developer branch started"

    Hello-World:
      needs: [start_developer_branch]
      runs-on: ubuntu-latest
      steps:
        - name: Hello World
          run: echo "Hello World"
